server:
  port: 8006
  servlet:
    context-path: /log
spring:
  application:
    name: log
  mvc:
    path-match:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://125.122.39.199:3306/manager?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zhice10905
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
